server:
  addr: ":8080"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "60s"

logger:
  engine: "slog"
  level: "info"

gin:
  mode: "debug"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "salestracker"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "5m"
